### ISSUE TITLE
Need an erazer for the black board

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#1]
Using the black board we are able to write but unable to eraze the contents

**Comment by AshuwinB** [comment]
Hey Dhanush! assign me this issue pls

**Comment by abhijeetanand29** [comment]
Please assign me this issue

**Comment by DhanushNehru** [comment]
Hey @abhijeetanand29 ,

@AshuwinB is already working on this

**Comment by DhanushNehru** [comment]
Please raise a new issue on clear button style @BharatChotwani

**Comment by BharatChotwani** [comment]
Okay @DhanushNehru

**Comment by tokyo3001** [comment]
@DhanushNehru Can you assign me this issue?

**Comment by Hriishikeshh** [comment]
can you assign this to me ill give a try under hacktoberfest2024
