### ISSUE TITLE
Create CONTRIBUTION.md file

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#44]

**Comment by MeetThakur** [comment]
on it

**Comment by MeetThakur** [comment]
done @DhanushNehru

**Comment by Keith-Web3** [comment]
Hello Dhanush, can I be assigned this issue?

**Comment by Keith-Web3** [comment]
@DhanushNehru seems there's already contribution.md file. It was just named incorrectly https://github.com/DhanushNehru/board/blob/main/Contributor.md
