### ISSUE TITLE
Add 'Stars on Github' display in the site

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#47]
Add option like this to get the live starts count of this repo in the board website

![Screenshot 2023-10-04 at 8 37 37 PM](https://github.com/DhanushNehru/board/assets/22955675/e6dcb3f8-cdbb-40d8-8259-4d2e1b9827ba)

**Comment by annesnour03** [comment]
Sure, I'll try to pick this up.

**Comment by madm234** [comment]
I can do this.

**Comment by Sha1kh4** [comment]
Hey i can create one like this :![image](https://github.com/DhanushNehru/board/assets/117739824/c00ca80e-2eff-4039-9dd9-5e51d9a6ff33) If thats okay please assign me this so i can create a PR
