### ISSUE TITLE
Need sign in with google option

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#49]
Need sign in with google option and only people who have signed in should view the board

**Comment by zainbinfurqan** [comment]
@DhanushNehru  can i work on this issue?

**Comment by amrahs02** [comment]
Hello  @DhanushNehru , I noticed that the assigned contributor hasn't provided any updates on the issue for a week. Would it be possible to reassign it to me so I can help move it forward?

**Comment by amrahs02** [comment]
@DhanushNehru Could you please provide some explanations about the issue? Thank you.

**Comment by DhanushNehru** [comment]
Only people who have signed in with Google should be able to use this board @amrahs02

**Comment by JeevaRamanathan** [comment]
Hi @DhanushNehru, I have a doubt. Should the drawings be associated with each individual user who is logged in, or should they be linked to just Google login based on the user's browser session

**Comment by DhanushNehru** [comment]
Any approach is fine with me @JeevaRamanathan

**Comment by JeevaRamanathan** [comment]
As this issue is still open, I have added a solution and raised a PR @DhanushNehru
