### ISSUE TITLE
Need UI / UX enhancement 

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#63]
The current UI needs improvement, open to ideas

**Comment by uxbysharon** [comment]
Hi @DhanushNehru , could you assign this issue to me? I'd like to work on this

**Comment by debianbaker** [comment]
Hi Dhanush. Can you assign this issue to me?

**Comment by kmahesh18** [comment]
@DhanushNehru assign me under hacktoberfest
