### ISSUE TITLE
[feat] Implement CI Pipeline for Linting

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/board#68]
We need to set up a Continuous Integration (CI) pipeline for our project to ensure code quality and consistency. The CI pipeline should run linting checks automatically and fix any issues when possible.

### Configure Linting:

- Ensure npm run lint is set up to check for code style and quality issues.
- Ensure npm run lint:fix is set up to automatically fix linting issues.

### Set Up CI Pipeline:

- Integrate a CI service (e.g., GitHub Actions, Travis CI, CircleCI) with our repository.
- Create a configuration file (e.g., .github/workflows/lint.yml for GitHub Actions) to run linting commands on every push and pull request.

### Expected Outcome:

- Automated linting checks on each commit and pull request.
- Consistent code style and reduced manual linting effort.

### Additional Notes:

- Ensure the pipeline is set up to provide clear feedback on linting errors.
- Optionally, set up a badge in the README to display the CI status.

**Comment by TheCoderAdi** [comment]
I have added a PR to it , Please review the changes.

**Comment by TheCoderAdi** [comment]
Hey @DhanushNehru,

I’ve resolved the issue with the linting pipeline. If you come across any further errors, feel free to reach out to me.

I’ve also attached a screenshot for your reference.
![image](https://github.com/user-attachments/assets/46a80a18-7153-43ea-9f84-29ddf43b68d0)

**Comment by DhanushNehru** [comment]
Thanks @TheCoderAdi

**Comment by TheCoderAdi** [comment]
> Thanks @TheCoderAdi

I appreciate your acknowledgment. I'm glad I could contribute.
